### ISSUE TITLE
Wrong license discovered

### ISSUE THREAD

**Issue by marcelotrevisani** [conda-incubator/grayskull#112]
- ``pytest-django``: found BSD-4 and it should be 3
- ``humanize`` found the wrong license
- ``adlfs`` found ``BSD-1-Clause`` and it should be ``BSD-3-Clause``

cc: @ocefpaf

**Comment by ocefpaf** [comment]
There is also the case of "aggressive" finding a license file. We should probably avoid looking into hidden directories. This is the case for `sat-stac`, a bad tarball with the `.egg`.

```
license_file: .eggs/pytest_runner-5.2-py3.8.egg/EGG-INFO/LICENSE
```

**Comment by marcelotrevisani** [comment]
> There is also the case of "aggressive" finding a license file. We should probably avoid looking into hidden directories. This is the case for `sat-stac`, a bad tarball with the `.egg`.
> 
> ```
> license_file: .eggs/pytest_runner-5.2-py3.8.egg/EGG-INFO/LICENSE
> ```

I thought I had removed the search in hidden folders. I will take a look on that later as well, thanks!

**Comment by ocefpaf** [comment]
Try `sat-stac`, if you don't get the bad license I may have an outdated version of grayskull.

PS: I'm working with upstream to fix it so you'll have to lock on the current version 0.4.0.

**Comment by maresb** [comment]
Here is [a potentially really tricky case](https://github.com/conda-forge/staged-recipes/pull/14666#discussion_r618690318) where a BSD 2-clause was interpreted as a 3-clause. [Actual license file](https://github.com/sphinx-contrib/confluencebuilder/blob/master/LICENSE)

**Comment by marcelotrevisani** [comment]
> Here is [a potentially really tricky case](https://github.com/conda-forge/staged-recipes/pull/14666#discussion_r618690318) where a BSD 2-clause was interpreted as a 3-clause. [Actual license file](https://github.com/sphinx-contrib/confluencebuilder/blob/master/LICENSE)

indeed, the heuristic can be improved to discover the right licence. Currently, Grayskull is using a fuzzy matching system where it tries to compare the licence found in the project with the most common licences out there.

**Comment by marcelotrevisani** [comment]
all the packages mentioned are getting the right licence now
closing this for now, if you find another one, please open a new issue or reopen this please
