### ISSUE TITLE
Move to regro/conda-forge?

### ISSUE THREAD

**Issue by CJ-Wright** [conda-incubator/grayskull#145]
Would it be possible to move this project to regro?

**Comment by marcelotrevisani** [comment]
What are the gains behind it? Why not move it to ``conda-forge``?

As ``conda-smithy`` and other tools are already in ``conda-forge`` for me it makes more sense to be there.

**Comment by CJ-Wright** [comment]
`conda-forge` works for me.

**Comment by marcelotrevisani** [comment]
I think we should discuss that in the next ``conda-forge`` meeting then :)

**Comment by marcelotrevisani** [comment]
Closing this as it is on ``conda-incubator`` :)

**Comment by CJ-Wright** [comment]
Thank you!
