### ISSUE TITLE
[BUG] Sometimes package names with hyphens use underscores for import

### ISSUE THREAD

**Issue by step21** [conda-incubator/grayskull#180]
**Describe the bug**
In a name such as package-name, import will be often package_name and pypi url will be a mix of both.

**To Reproduce**
Use grayskull to make a recipe for eth-abi

**Expected behavior**
Right module name is imported.

**Environment:**
 - grayskull --version = 0.7.3

**Additional context**
Example url https://pypi.org/project/eth-abi/

**Comment by marcelotrevisani** [comment]
Thanks again for reporting it!

Related to https://github.com/marcelotrevisani/grayskull/issues/150

**Comment by marcelotrevisani** [comment]
That was fixed a while ago but I forgot to close it, sorry.
