### ISSUE TITLE
Moving recipe responsibility to another project

### ISSUE THREAD

**Issue by marcelotrevisani** [conda-incubator/grayskull#183]
Hi folks, (@ocefpaf, @mariusvniekerk , @wolfv )

I was working to move all the part responsible to deal with the recipe (comments, jinja, sections, constrains, selectors, ...) to a separated to project. Initially I thought to call that as ``masterchef`` but as @ocefpaf alerted about trademark infringements I am renaming it to ``souschef ``, I think it is a good name as well.  :D

I would like to know if any of you are interested on it and have suggestions about the interface to deal with the recipe.

I did some code here but I decided to redo some work/design.

Initially, I was thinking to have a class recipe which is basically a collection of sections, comments and jinja.
so I thought that would be nice to have something like
```python
# Recipe object
print(recipe)
[JinjaObj, SectionObj, CommentObj]
```
but behind the scenes the module will be just handling the ruamel yaml object.

So it will also be able to access the sections directly by the name using for example:
```python
recipe.requirements
# or
recipe["requirements"]
```

and the Section class will be using the Recipe class as composition but with the possibility to add comments or selectors to the section. it will have another class to handle the items which a section may have, this item attribute you will be able to add comments, selectors or constrains. 
Some functionalities such as the responsibility to handle comments, constrains and selector will be design to be ``mixin``

I don't know if I was clear, but I would like some suggestions of interfaces/how do you think it would be nice to handle the recipe and things like that :)

**Comment by mariusvniekerk** [comment]
One really handy thing would be to add degree of control for the jinja / selector stuff.

There is some fairly fancy stuff for doing this in the auto tick bot.

Moving that over would help

**Comment by marcelotrevisani** [comment]
that would be nice to also add support for it in ``souschef``
the jinja part is quite simple, just set and add global jinja variables

I am closing this as I already refactored ``grayskull`` to use ``souschef``
https://github.com/marcelotrevisani/souschef
