### ISSUE TITLE
[BUG] Empty entry point found

### ISSUE THREAD

**Issue by Anthchirp** [conda-incubator/grayskull#194]
**Describe the bug**
Sometimes recipes contain an invalid empty entry point

**To Reproduce**
1. Go to https://www.marcelotrevisani.com/grayskull
2. Run for `modulegraph` 0.18
3. See
```yaml
  entry_points:
    - ''
    - modulegraph = modulegraph.__main__:main
```

**Expected behavior**
```yaml
  entry_points:
    - modulegraph = modulegraph.__main__:main
```

**Additional context**
Can't really see where this comes from. The package `setup.cfg` is looking fine:
https://github.com/ronaldoussoren/modulegraph/blob/e4a51fb920a410643ba74f6eb338f387986482aa/setup.cfg#L34-L35

**Comment by marcelotrevisani** [comment]
For sure it is a bug!
Thanks for reporting it again, I really appreciate it!

**Comment by marcelotrevisani** [comment]
It should be fixed by https://github.com/conda-incubator/grayskull/pull/198

**Comment by marcelotrevisani** [comment]
Just to let you know that I already fixed both bugs which you reported
I generated the version ``0.8.3`` and I also updated the webservice on my personal website
