### ISSUE TITLE
[BUG] Invalid certificate on marcelotrevisani.com/grayskull

### ISSUE THREAD

**Issue by BastianZim** [conda-incubator/grayskull#217]
**Describe the bug**

When generating a recipe with https://www.marcelotrevisani.com/grayskull a certificate error is returned.

**To Reproduce**
1. Go to https://www.marcelotrevisani.com/grayskull
2. Enter package
3. See error

**Expected behavior**

The certificate should be generated.

**Outputs**
If applicable, add the output to help explain your problem.

Safari:
Error - requests
The certificate for this server is invalid. You might be connecting to a server that is pretending to be “marcelotrevisani.info”, which could put your confidential information at risk.

Chrome:
Error - requests
Failed to fetch

Firefox:
Error - requests
NetworkError when attempting to fetch resource.

**Environment:**
 - website

**Additional context**

Hi @marcelotrevisani,
sorry if this is the wrong place to file this. Let me know if I should file it somewhere else or close it entirely.

**Comment by marcelotrevisani** [comment]
Hi @BastianZim , that is the right place, don't worry! :)

Yes, it is not working indeed, I believe it is because my SSL certificate has expired, I renewed but it seems I missed something
I will take a look at that, thanks for reporting it! 

Any updates I will keep you posted.

**Comment by BastianZim** [comment]
Perfect, thank you! :)

**Comment by marcelotrevisani** [comment]
I updated the SSL certificates and the configuration on the webserver, it is working now :tada: 

Thanks for reporting it! :smiley: 

If the problem persists or if you encounter any other problem please let me know

**Comment by BastianZim** [comment]
Confirmed working, thanks for the quick fix! 🎉😃
