### ISSUE TITLE
[BUG] grayskull pypi jsons failure. 

### ISSUE THREAD

**Issue by ngodber** [conda-incubator/grayskull#221]
**Describe the bug**
Receive the following failure when attempting to use grayskull to general recipe for 'jsons' pypi package. AttributeError: Hash information for sdist was not found on PyPi metadata.

Presumably a bug as no indication of missing hash on pypi side:

![image](https://user-images.githubusercontent.com/11834846/114259609-849e7c80-9a12-11eb-8cce-330d680cb518.png)

**To Reproduce**
1. grayskull pypi jsons
**Expected behavior**
Creation of 

**Outputs**
If applicable, add the output to help explain your problem.

**Environment:**
 - conda list
# packages in environment at 
#
# Name                    Version                   Build  Channel
alabaster                 0.7.12                     py_0    conda-forge
astroid                   2.5.2            py38haa244fe_0    conda-forge
attrs                     20.3.0             pyhd3deb0d_0    conda-forge
babel                     2.9.0              pyhd3deb0d_0    conda-forge
beautifulsoup4            4.9.3              pyhb0f4dca_0    conda-forge
boost-cpp                 1.74.0               h54f0996_2    conda-forge
brotlipy                  0.7.0           py38h294d835_1001    conda-forge
bzip2                     1.0.8                h8ffe710_4    conda-forge
ca-certificates           2020.12.5            h5b45459_0    conda-forge
cairo                     1.16.0            hb19e0ff_1008    conda-forge
certifi                   2020.12.5        py38haa244fe_1    conda-forge
cffi                      1.14.5           py38hd8c33c5_0    conda-forge
cfitsio                   3.470                h0af3d06_7    conda-forge
chardet                   4.0.0            py38haa244fe_1    conda-forge
click                     7.1.2              pyh9f0ad1d_0    conda-forge
click-plugins             1.1.1                      py_0    conda-forge
cligj                     0.7.1              pyhd8ed1ab_0    conda-forge
colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
conda                     4.10.0           py38haa244fe_1    conda-forge
conda-build               3.21.4           py38haa244fe_0    conda-forge
conda-package-handling    1.7.2            py38h8934438_0    conda-forge
console_shortcut          0.1.1                         4
cryptography              3.4.7            py38hd7da0ea_0    conda-forge
curl                      7.76.0               hf1763fc_0    conda-forge
docutils                  0.17             py38haa244fe_0    conda-forge
expat                     2.3.0                h39d44d4_0    conda-forge
filelock                  3.0.12             pyh9f0ad1d_0    conda-forge
fiona                     1.8.18           py38h91b197a_1    conda-forge
fontconfig                2.13.1            h1989441_1004    conda-forge
freetype                  2.10.4               h546665d_1    conda-forge
freexl                    1.0.6                ha8e266a_0    conda-forge
gdal                      3.2.2            py38hacca965_2    conda-forge
geopandas                 0.9.0              pyhd8ed1ab_0    conda-forge
geos                      3.9.1                h39d44d4_2    conda-forge
geotiff                   1.6.0                h8e90983_5    conda-forge
gettext                   0.19.8.1          h1a89ca6_1005    conda-forge
git                       2.30.2               h57928b3_1    conda-forge
glob2                     0.7                        py_0    conda-forge
grayskull                 0.8.5              pyhd8ed1ab_0    conda-forge
hdf4                      4.2.13            h0e5069d_1004    conda-forge
hdf5                      1.10.6          nompi_h5268f04_1114    conda-forge
icu                       68.1                 h0e60522_0    conda-forge
idna                      2.10               pyh9f0ad1d_0    conda-forge
imagesize                 1.2.0                      py_0    conda-forge
intel-openmp              2020.3             h57928b3_311    conda-forge
isort                     5.8.0              pyhd8ed1ab_0    conda-forge
jinja2                    2.11.3             pyh44b312d_0    conda-forge
jpeg                      9d                   h8ffe710_0    conda-forge
kealib                    1.4.14               h96bfa42_2    conda-forge
krb5                      1.17.2               hbae68bd_0    conda-forge
lazy-object-proxy         1.6.0            py38h294d835_0    conda-forge
libarchive                3.5.1                h8686738_1    conda-forge
libblas                   3.9.0                     8_mkl    conda-forge
libcblas                  3.9.0                     8_mkl    conda-forge
libcurl                   7.76.0               hf1763fc_0    conda-forge
libffi                    3.3                  h0e60522_2    conda-forge
libgdal                   3.2.2                h48ef39c_2    conda-forge
libglib                   2.68.0               h1e62bf3_2    conda-forge
libiconv                  1.16                 he774522_0    conda-forge
libkml                    1.3.0             h9859afa_1013    conda-forge
liblapack                 3.9.0                     8_mkl    conda-forge
liblief                   0.10.1               ha925a31_2    conda-forge
libnetcdf                 4.7.4           nompi_h3a9aa94_107    conda-forge
libpng                    1.6.37               h1d00b33_2    conda-forge
libpq                     13.1                 h4f54205_2    conda-forge
librttopo                 1.1.0                hb340de5_6    conda-forge
libspatialindex           1.9.3                h39d44d4_3    conda-forge
libspatialite             5.0.1                h6b539a6_4    conda-forge
libssh2                   1.9.0                h680486a_6    conda-forge
libtiff                   4.2.0                hc10be44_0    conda-forge
libwebp-base              1.2.0                h8ffe710_2    conda-forge
libxml2                   2.9.10               hf5bbc77_3    conda-forge
lz4-c                     1.9.3                h8ffe710_0    conda-forge
lzo                       2.10              he774522_1000    conda-forge
m2-msys2-runtime          2.5.0.17080.65c939c               3    conda-forge
m2-patch                  2.7.5                         2    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
markupsafe                1.1.1            py38h294d835_3    conda-forge
mccabe                    0.6.1                      py_1    conda-forge
menuinst                  1.4.16           py38he774522_1
mkl                       2020.4             hb70f87d_311    conda-forge
msys2-conda-epoch         20160418                      1    conda-forge
munch                     2.5.0                      py_0    conda-forge
numpy                     1.20.2           py38h09042cb_0    conda-forge
openjpeg                  2.4.0                h48faf41_0    conda-forge
openssl                   1.1.1k               h8ffe710_0    conda-forge
packaging                 20.9               pyh44b312d_0    conda-forge
pandas                    1.2.3            py38h4c96930_0    conda-forge
pcre                      8.44                 ha925a31_0    conda-forge
pip                       21.0.1             pyhd8ed1ab_0    conda-forge
pixman                    0.40.0               h8ffe710_0    conda-forge
pkginfo                   1.7.0              pyhd8ed1ab_0    conda-forge
poppler                   21.03.0              h9ff6ed8_0    conda-forge
poppler-data              0.4.10                        0    conda-forge
postgresql                13.1                 h0f1a9bc_2    conda-forge
powershell_shortcut       0.0.1                         3
progressbar2              3.53.1             pyh9f0ad1d_0    conda-forge
proj                      8.0.0                h1cfcee9_0    conda-forge
psutil                    5.8.0            py38h294d835_1    conda-forge
py-lief                   0.10.1           py38h4b9bc1a_2    conda-forge
pycosat                   0.6.3           py38h294d835_1006    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pygments                  2.8.1              pyhd8ed1ab_0    conda-forge
pylint                    2.7.2            py38haa244fe_0    conda-forge
pyopenssl                 20.0.1             pyhd8ed1ab_0    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyproj                    3.0.1            py38he394cdd_1    conda-forge
pysocks                   1.7.1            py38haa244fe_3    conda-forge
python                    3.8.8                hdbf39b2_4
python-dateutil           2.8.1                      py_0    conda-forge
python-libarchive-c       2.9              py38haa244fe_2    conda-forge
python-utils              2.5.6              pyh44b312d_0    conda-forge
python_abi                3.8                      1_cp38    conda-forge
pytz                      2021.1             pyhd8ed1ab_0    conda-forge
pywin32                   300              py38h294d835_0    conda-forge
pyyaml                    5.4.1            py38h294d835_0    conda-forge
rapidfuzz                 0.12.5           py38hb99c5c2_0    conda-forge
requests                  2.25.1             pyhd3deb0d_0    conda-forge
ripgrep                   12.1.1               h301d43c_1    conda-forge
rtree                     0.9.7            py38h8b54edf_1    conda-forge
ruamel.yaml               0.16.12          py38h294d835_2    conda-forge
ruamel.yaml.clib          0.2.2            py38h294d835_2    conda-forge
ruamel.yaml.jinja2        0.2.4                      py_1    conda-forge
ruamel_yaml               0.15.80         py38h294d835_1004    conda-forge
setuptools                49.6.0           py38haa244fe_3    conda-forge
shapely                   1.7.1            py38h2426642_4    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
snowballstemmer           2.1.0              pyhd8ed1ab_0    conda-forge
soupsieve                 2.0.1                      py_1    conda-forge
sphinx                    3.5.3              pyhd8ed1ab_0    conda-forge
sphinxcontrib-applehelp   1.0.2                      py_0    conda-forge
sphinxcontrib-devhelp     1.0.2                      py_0    conda-forge
sphinxcontrib-htmlhelp    1.0.3                      py_0    conda-forge
sphinxcontrib-jsmath      1.0.1                      py_0    conda-forge
sphinxcontrib-qthelp      1.0.3                      py_0    conda-forge
sphinxcontrib-serializinghtml 1.1.4                      py_0    conda-forge
sqlite                    3.35.3               h8ffe710_0    conda-forge
stdlib-list               0.7.0                      py_2    conda-forge
tiledb                    2.2.7                hf84e3da_0    conda-forge
tk                        8.6.10               h8ffe710_1    conda-forge
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
tqdm                      4.59.0             pyhd8ed1ab_0    conda-forge
urllib3                   1.26.4             pyhd8ed1ab_0    conda-forge
vc                        14.2                 hb210afc_4    conda-forge
vs2015_runtime            14.28.29325          h5e1d092_4    conda-forge
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
win_inet_pton             1.1.0            py38haa244fe_2    conda-forge
wincertstore              0.2             py38haa244fe_1006    conda-forge
wrapt                     1.12.1           py38h294d835_3    conda-forge
xerces-c                  3.2.3                h0e60522_2    conda-forge
xz                        5.2.5                h62dcd97_1    conda-forge
yaml                      0.2.5                he774522_0    conda-forge
zlib                      1.2.11            h62dcd97_1010    conda-forge
zstd                      1.4.9                h6255e5f_0    conda-forge

 - grayskull --version 0.8.5

**Additional context**

**Comment by BastianZim** [comment]
Probably the same problem as in #209.
Grayskull needs a sdist file but only a wheel is available on PyPI: https://pypi.org/project/jsons/

**Comment by ngodber** [comment]
ahh, yes, just saw that *facepalm*. Sorry!

**Comment by BastianZim** [comment]
No worries, I made the same mistake first.
