### ISSUE TITLE
[BUG] Incorrect dependency versions

### ISSUE THREAD

**Issue by spinoch** [conda-incubator/grayskull#222]
**Describe the bug**
Grayskull returns incorrect dependency versions for transitive dependencies.

**To Reproduce**
1. Run `BROWNIE_LIB=1 grayskull pypi eth-brownie` (see https://github.com/eth-brownie/brownie/issues/991#issuecomment-800512237 the meaning of this env variable)
2. See hard-pinning of transitive dependencies, as specified in `requirments.txt` but not in `requirements.in`
e.g. grayskull requires
`  - lru-dict ==1.1.7`
while pip says
`Requirement already satisfied: lru-dict<2.0.0,>=1.1.6 in /opt/conda/lib/python3.8/site-packages (from web3==5.11.1->eth-brownie) (1.1.6)`
3. See also, incorrect syntax (missing space between package name and version specification): `  - eth-hash<1`

**Expected behavior**
Only dependencies from `requirements.in` are taken, as pip does (see also: https://github.com/eth-brownie/brownie/blob/da078f93002397cf16d5bb566c9a38b0f1234431/setup.py#L10)

**Outputs**
If applicable, add the output to help explain your problem.

**Environment:**
<details>
<summary>conda list</summary>
# packages in environment at /opt/conda:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
apipkg                    1.5                      pypi_0    pypi
appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
asttokens                 2.0.3                    pypi_0    pypi
attrs                     20.3.0                   pypi_0    pypi
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.3              pyhd8ed1ab_0    conda-forge
base58                    2.0.1                    pypi_0    pypi
beautifulsoup4            4.9.3              pyhb0f4dca_0    conda-forge
bitarray                  1.2.2                    pypi_0    pypi
black                     19.10b0                  pypi_0    pypi
bleach                    3.2.1                    pypi_0    pypi
blinker                   1.4                        py_1    conda-forge
boolean.py                3.7                        py_0    conda-forge
brotlipy                  0.7.0           py38h497a2fe_1001    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.17.1               h7f98852_1    conda-forge
ca-certificates           2020.12.5            ha878542_0    conda-forge
certifi                   2020.12.5        py38h578d9bd_1    conda-forge
cffi                      1.14.5           py38ha65f79e_0    conda-forge
chardet                   4.0.0            py38h578d9bd_1    conda-forge
click                     7.1.2              pyh9f0ad1d_0    conda-forge
colorama                  0.4.4                    pypi_0    pypi
conda                     4.10.1           py38h578d9bd_0    conda-forge
conda-build               3.21.4           py38h578d9bd_0    conda-forge
conda-forge-pinning       2021.04.17.14.54.41      hd8ed1ab_0    conda-forge
conda-package-handling    1.7.2            py38h8df0ef7_0    conda-forge
conda-smithy              3.10.0             pyhd8ed1ab_0    conda-forge
cryptography              3.4.7            py38ha5dfef3_0    conda-forge
curl                      7.76.1               h979ede3_1    conda-forge
cytoolz                   0.11.0                   pypi_0    pypi
dataclasses               0.8                pyhc8e2a94_1    conda-forge
decorator                 5.0.6              pyhd8ed1ab_0    conda-forge
deprecated                1.2.12             pyh44b312d_0    conda-forge
docutils                  0.16                     pypi_0    pypi
eth-abi                   2.1.1                    pypi_0    pypi
eth-account               0.5.2                    pypi_0    pypi
eth-event                 1.2.0                    pypi_0    pypi
eth-hash                  0.2.0                    pypi_0    pypi
eth-keyfile               0.5.1                    pypi_0    pypi
eth-keys                  0.3.3                    pypi_0    pypi
eth-rlp                   0.2.1                    pypi_0    pypi
eth-typing                2.2.2                    pypi_0    pypi
eth-utils                 1.9.5                    pypi_0    pypi
execnet                   1.7.1                    pypi_0    pypi
expat                     2.3.0                h9c3ff4c_0    conda-forge
filelock                  3.0.12             pyh9f0ad1d_0    conda-forge
gettext                   0.19.8.1          h0b5b191_1005    conda-forge
git                       2.30.2          pl5320h24fefe6_1    conda-forge
gitdb                     4.0.7              pyhd8ed1ab_0    conda-forge
gitpython                 3.1.14             pyhd8ed1ab_0    conda-forge
glob2                     0.7                        py_0    conda-forge
gmp                       6.2.1                h58526e2_0    conda-forge
gmpy2                     2.1.0b1          py38hd744826_1    conda-forge
hexbytes                  0.2.1                    pypi_0    pypi
hypothesis                5.35.0                   pypi_0    pypi
icu                       68.1                 h58526e2_0    conda-forge
idna                      2.10               pyh9f0ad1d_0    conda-forge
inflection                0.5.0                    pypi_0    pypi
iniconfig                 1.1.1                    pypi_0    pypi
ipfshttpclient            0.6.1                    pypi_0    pypi
ipython                   7.22.0           py38hd0cf306_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
isodate                   0.6.0                      py_1    conda-forge
jedi                      0.18.0           py38h578d9bd_2    conda-forge
jeepney                   0.4.3                    pypi_0    pypi
jinja2                    2.11.3             pyh44b312d_0    conda-forge
jsonschema                3.2.0                    pypi_0    pypi
keyring                   21.5.0                   pypi_0    pypi
krb5                      1.17.2               h926e7f8_0    conda-forge
ld_impl_linux-64          2.35.1               hea4e1c9_2    conda-forge
libarchive                3.5.1                h3f442fb_1    conda-forge
libcurl                   7.76.1               hc4aaa36_1    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libffi                    3.3                  h58526e2_2    conda-forge
libgcc-ng                 9.3.0               h2828fa1_18    conda-forge
libgomp                   9.3.0               h2828fa1_18    conda-forge
libiconv                  1.16                 h516909a_0    conda-forge
liblief                   0.10.1               he1b5a44_2    conda-forge
libnghttp2                1.43.0               h812cca2_0    conda-forge
libssh2                   1.9.0                ha56f1ee_6    conda-forge
libstdcxx-ng              9.3.0               h6de172a_18    conda-forge
libxml2                   2.9.10               h72842e0_4    conda-forge
license-expression        1.2                        py_0    conda-forge
lru-dict                  1.1.6                    pypi_0    pypi
lz4-c                     1.9.3                h9c3ff4c_0    conda-forge
lzo                       2.10              h516909a_1000    conda-forge
markupsafe                1.1.1            py38h497a2fe_3    conda-forge
more-itertools            8.7.0                    pypi_0    pypi
mpc                       1.1.0             h04dde30_1009    conda-forge
mpfr                      4.0.2                he80fd80_1    conda-forge
mpmath                    1.2.1              pyhd8ed1ab_0    conda-forge
msrest                    0.6.21             pyh44b312d_0    conda-forge
multiaddr                 0.0.9                    pypi_0    pypi
mypy_extensions           0.4.3            py38h578d9bd_3    conda-forge
mythx-models              1.9.1                    pypi_0    pypi
ncurses                   6.2                  h58526e2_4    conda-forge
netaddr                   0.8.0                    pypi_0    pypi
oauthlib                  3.0.1                      py_0    conda-forge
openssl                   1.1.1k               h7f98852_0    conda-forge
packaging                 20.4                     pypi_0    pypi
parsimonious              0.8.1                    pypi_0    pypi
parso                     0.8.2              pyhd8ed1ab_0    conda-forge
patchelf                  0.11                 he1b5a44_0    conda-forge
pathspec                  0.8.1              pyhd3deb0d_0    conda-forge
pcre                      8.44                 he1b5a44_0    conda-forge
pep517                    0.10.0           py38h578d9bd_0    conda-forge
perl                      5.32.0               h36c2ea0_0    conda-forge
pexpect                   4.8.0              pyh9f0ad1d_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pip                       21.0.1             pyhd8ed1ab_0    conda-forge
pip-tools                 6.1.0              pyhd8ed1ab_0    conda-forge
pkginfo                   1.6.1                    pypi_0    pypi
pluggy                    0.13.1                   pypi_0    pypi
prompt-toolkit            3.0.7                    pypi_0    pypi
protobuf                  3.14.0                   pypi_0    pypi
psutil                    5.7.3                    pypi_0    pypi
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
py                        1.9.0                    pypi_0    pypi
py-lief                   0.10.1           py38h348cfbe_2    conda-forge
py-solc-ast               1.2.5                    pypi_0    pypi
py-solc-x                 1.0.0                    pypi_0    pypi
pycosat                   0.6.3           py38h497a2fe_1006    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pycrypto                  2.6.1           py38h8df0ef7_1005    conda-forge
pycryptodome              3.9.9                    pypi_0    pypi
pygithub                  1.44             py38h32f6830_0    conda-forge
pygments                  2.6.1                    pypi_0    pypi
pygments-lexer-solidity   0.5.1                    pypi_0    pypi
pyjwt                     1.7.1                    pypi_0    pypi
pyopenssl                 20.0.1             pyhd8ed1ab_0    conda-forge
pyparsing                 2.4.7                    pypi_0    pypi
pyrsistent                0.17.3                   pypi_0    pypi
pysocks                   1.7.1            py38h578d9bd_3    conda-forge
pytest                    6.0.1                    pypi_0    pypi
pytest-forked             1.3.0                    pypi_0    pypi
pytest-xdist              1.34.0                   pypi_0    pypi
python                    3.8.8           hffdb5ce_0_cpython    conda-forge
python-dateutil           2.8.1                    pypi_0    pypi
python-libarchive-c       2.9              py38h578d9bd_2    conda-forge
python_abi                3.8                      1_cp38    conda-forge
pythx                     1.6.1                    pypi_0    pypi
pytz                      2021.1             pyhd8ed1ab_0    conda-forge
pyyaml                    5.3.1                    pypi_0    pypi
readline                  8.0                  he28a2e2_2    conda-forge
readme-renderer           28.0                     pypi_0    pypi
regex                     2021.4.4         py38h497a2fe_0    conda-forge
requests                  2.25.1             pyhd3deb0d_0    conda-forge
requests-oauthlib         1.3.0              pyh9f0ad1d_0    conda-forge
requests-toolbelt         0.9.1                    pypi_0    pypi
rfc3986                   1.4.0                    pypi_0    pypi
ripgrep                   12.1.1               h516909a_1    conda-forge
rlp                       1.2.0                    pypi_0    pypi
ruamel.yaml               0.16.12          py38h497a2fe_2    conda-forge
ruamel.yaml.clib          0.2.2            py38h497a2fe_2    conda-forge
ruamel_yaml               0.15.80         py38h497a2fe_1004    conda-forge
scrypt                    0.8.18           py38h2b97feb_0    conda-forge
secretstorage             3.2.0                    pypi_0    pypi
semantic-version          2.8.5                    pypi_0    pypi
setuptools                49.6.0           py38h578d9bd_3    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
smmap                     3.0.5              pyh44b312d_0    conda-forge
sortedcontainers          2.3.0                    pypi_0    pypi
soupsieve                 2.0.1                      py_1    conda-forge
sqlite                    3.35.4               h74cdb3f_0    conda-forge
sympy                     1.7.1            py38h578d9bd_1    conda-forge
tk                        8.6.10               h21135ba_1    conda-forge
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
toolz                     0.11.1                     py_0    conda-forge
tqdm                      4.48.2                   pypi_0    pypi
traitlets                 5.0.5                      py_0    conda-forge
twine                     3.2.0                    pypi_0    pypi
typed-ast                 1.4.2            py38h497a2fe_0    conda-forge
typing_extensions         3.7.4.3                    py_0    conda-forge
urllib3                   1.26.4             pyhd8ed1ab_0    conda-forge
varint                    1.0.2                    pypi_0    pypi
vsts-python-api           0.1.22                     py_0    conda-forge
vvm                       0.1.0                    pypi_0    pypi
vyper                     0.2.7                    pypi_0    pypi
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
web3                      5.11.1                   pypi_0    pypi
webencodings              0.5.1                    pypi_0    pypi
websockets                8.1                      pypi_0    pypi
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
wrapt                     1.12.1           py38h497a2fe_3    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
yaml                      0.2.5                h516909a_0    conda-forge
zlib                      1.2.11            h516909a_1010    conda-forge
zstd                      1.4.9                ha95c52a_0    conda-forge

</details>

 - grayskull --version: 0.8.5

**Comment by marcelotrevisani** [comment]
Indeed, there are a couple of problems there.

gonna add this bug to my todo list for the next month, thanks for reporting it! :)

**Comment by marcelotrevisani** [comment]
It seems to be fine now, it is following what it is in the metadata.
Closing it for now, but if you think this problem still persists please let me know
