### ISSUE TITLE
Confusing comment in the _injection_disutils method of the PyPI class

### ISSUE THREAD

**Issue by ForgottenProgramme** [conda-incubator/grayskull#233]
See [here](https://github.com/conda-incubator/grayskull/blob/0fc0cc725ba6e8a37b901d8d36cf6603b8cd7abc/grayskull/pypi/pypi.py#L200).

"This method is necessary because some information are missing from the
pypi metadata and also for those packages which the pypi metadata is missing. "

@marcelotrevisani , would you please clarify what it's trying to say, specially in the second line?

**Comment by marcelotrevisani** [comment]
that should be
```
This method is necessary because some information might be missing from the
pypi metadata and also for those packages which the pypi metadata is not present 
on the pypi API.
```

**Comment by marcelotrevisani** [comment]
some packages does not return metadata from the pypi API so it is necessary to patch the distutils to recover the information from setup.py
