### ISSUE TITLE
Clarify grayskull instructions on conda-forge blog

### ISSUE THREAD

**Issue by zzhengnan** [conda-incubator/grayskull#235]
Thanks for this awesome tool! I was directed here by the conda-forge blog https://conda-forge.org/blog/posts/2021-06-16-graykull-step-by-step/.

A few suggestions for the instructions. I believe the second one is _required_; currently the instructions don't mention that the user needs to cd into the recipes directory, resulting in the auto-generated folder being located _outside_ the desired directory.

```diff
- 2. Fetch a new branch from the master branch.
+ 2. Create ...

- 4. Through CLI enter inside the ‘staged-recipes’ directory.
+ 4. cd into the `staged-recipes/recipes` directory.
```

**Comment by ForgottenProgramme** [comment]
@zzhengnan, you are right. Thanks for pointing it out! 
Just so you know, the blog is written by conda-forge and is hosted on the conda-forge docs, the correct place to report this issue is https://github.com/conda-forge/conda-forge.github.io . :)

**Comment by ForgottenProgramme** [comment]
The blog is now updated. 
I'll close this issue. :)
