### ISSUE TITLE
[BUG] Incorrect certificate for web version

### ISSUE THREAD

**Issue by BastianZim** [conda-incubator/grayskull#239]
**Describe the bug**

https://www.marcelotrevisani.com/grayskull has the following error: 

```
Error - WeasyPrint
The certificate for this server is invalid. You might be connecting to a server that is pretending to be “marcelotrevisani.info”, which could put your confidential information at risk.
```

**To Reproduce**

**Expected behavior**

**Outputs**
If applicable, add the output to help explain your problem.

**Environment:**
 - conda list
 - pip list
 - grayskull --version

**Additional context**

Not sure if this is the right place to report this but wasn't sure where else. 😄

**Comment by marcelotrevisani** [comment]
I forgot to add a reminder in my calendar to update the SSL certificate. I will do it now.

I use a free platform to generate the SSL certificates, every three months, I think, I need to renew it.

**Comment by marcelotrevisani** [comment]
That should be fixed now.
Thanks for reporting it! :)

**Comment by BastianZim** [comment]
Ahh ok - thank you! :)
