### ISSUE TITLE
[FEATURE] facilities for post-processing editing of meta.yaml

### ISSUE THREAD

**Issue by sgbaird** [conda-incubator/grayskull#254]
**Is your feature request related to a problem? Please describe.**
A lot of issues might be addressed by some post-processor functionality (or a guide for post-processing) the `meta.yaml` files produced by `grayskull`. This would be particularly useful for CI setups I think.

**Describe the solution you'd like**
After `meta.yaml` is processed, edit the file using python code or CLI so as to add certain values to certain fields.

**Additional context**
#253 #243

**Comment by marcelotrevisani** [comment]
Closing this in favor of ``souschef``
