### ISSUE TITLE
Maintaining dependency order

### ISSUE THREAD

**Issue by jakirkham** [conda-incubator/grayskull#259]
**Is your feature request related to a problem? Please describe.**

When looking at diffs of dependencies, sometimes they are hard to reason about due to reordering of the dependencies. Additionally some dependencies (like `python` tend to get listed first to make it easier to see they are there (and not forgotten) with any relevant version constraints.

**Describe the solution you'd like**

It would help if grayskull was able to maintain the dependency order as much as possible. This would keep diffs more compact and making it easier to catch any errors (like C/C++ dependencies that got dropped).

**Describe alternatives you've considered**

One alternative instead of following the recipe order would be to follow the `setup.py` order. As maintainers are often comparing the two, this actually makes that comparison easier. Though if the recipe is doing something different, this might be off for the first PR still

Feel free to suggest alternatives.

**Additional context**

Have made and looked at a few PRs with Grayskull recently and this behavior has resulted in some confusion.

**Comment by maresb** [comment]
See https://github.com/conda-incubator/grayskull/pull/372. I still sort the dependencies, if it gets merged, it would be trivial to remove the `sorted()` call.
