### ISSUE TITLE
First two lines of the recipe become one when using the github source

### ISSUE THREAD

**Issue by ocefpaf** [conda-incubator/grayskull#263]
@ForgottenProgramme I tried to find the source of the bug but failed miserably, sorry :-(

When creating recipes with a github source, say,

```
grayskull pypi --strict-conda-forge https://github.com/TEOS-10/GSW-Python
```

we get:

```
{% set name = "GSW-Python" %}{% set version = "3.4.1.post0" %}
```

We need a line break there.

PS: conda-forge linter fails to catch that :scream:

**Comment by marcelotrevisani** [comment]
True, I didn't pay attention to this. I will take a look. 

By the way, ``souschef`` can handle this case of having jinja in the same line :D

**Comment by marcelotrevisani** [comment]
Closing this as it was fixed
