### ISSUE TITLE
Initial support for R pakcages.

### ISSUE THREAD

**Issue by ocefpaf** [conda-incubator/grayskull#266]
Ideally we should do a proper "light-weight" re-write of the `conda-skeleton cran` as it was done for `conda-skeleton pypi` but as a first iteration having something for R is better than nothing and here is what I'm thinking:

- add conda-build as an optional dependency
- if a user calls "cran" run `conda-skeleton cran` (or warn about the missing optional dep)
- run the [`conda_r_skeleton_helper`](https://github.com/bgruening/conda_r_skeleton_helper)

@marcelotrevisani this would improve the user experience b/c it will be a single package to create both recipes and help reviews b/c the `conda_r_skeleton_helper` would be applied already. What do you think?

xref.: step 2 from https://conda-forge.org/docs/maintainer/adding_pkgs.html?highlight=cran#getting-started

**Comment by ForgottenProgramme** [comment]
@ocefpaf, I think this is a good plan.

**Comment by ForgottenProgramme** [comment]
"a first iteration having something for R is better than nothing"
This makes sense. Implementing this would mean that the user doesn't need to use two separate recipe generators for Python and R recipes. And although this will be an enhancement in user experience, Grayskull would be using conda-skeleton (which is integrated with conda-build) under the hood to generate the recipe. And this, as I realized after a discussion with @marcelotrevisani, would, unfortunately, defeat the purpose of creating Grayskull (a stand alone, conda-build independent application) in the first place. 
Perhaps, when the user runs "cran", displaying a message like: `Grayskull doesn't support CRAN packages yet. You might want to try conda-skeleton for generating R recipes.` might be good idea while we work on implementing the R support in Grayskull.

**Comment by marcelotrevisani** [comment]
Closing this as it is duplicated with https://github.com/conda-incubator/grayskull/issues/266 and https://github.com/conda-incubator/grayskull/pull/349
