### ISSUE TITLE
[FEATURE] Translate ~= to PEP 440

### ISSUE THREAD

**Issue by BastianZim** [conda-incubator/grayskull#270]
**Is your feature request related to a problem? Please describe.**

Some packages specify a dependency according to PEP 440 like this: `~=`
Conda-build does not support this: https://docs.conda.io/projects/conda-build/en/latest/resources/package-spec.html#build-version-spec

**Describe the solution you'd like**

`~=` should get translated to `>= V.N, == V.*`

**Describe alternatives you've considered**

Do it manually.

**Additional context**

https://stackoverflow.com/a/39590286

**Comment by BastianZim** [comment]
This is already, if I remember correctly, being done for poetry and it's `^` specifier. Haven't been able to find the code but maybe it could be added there.

**Comment by marcelotrevisani** [comment]
yeah, we need to change it
I am working in a huge refactoring for grayskull to simplify some stuffs to be easier to expand it and to also use it as a lib/module

after that we can definitely take a look on this, as you mentioned we can replace it by ``>= V.N, == V.*``

**Comment by BastianZim** [comment]
Great, thank you!

**Comment by marcelotrevisani** [comment]
Do you know a package that uses ``~=``?

**Comment by BastianZim** [comment]
Thanks for adding that. One example is https://github.com/conda-forge/staged-recipes/pull/17358
