### ISSUE TITLE
[FEATURE] Add support to build recipe from local sdist

### ISSUE THREAD

**Issue by beenje** [conda-incubator/grayskull#272]
**Is your feature request related to a problem? Please describe.**
At work we have many pure python packages that we'd like to deploy with conda.
Having people add a conda recipe is an extra step and often seen as duplicate work. For most packages the recipe should be quite straightforward and needed information already available in the setup.py or setup.cfg file.

**Describe the solution you'd like**
I'd like to generate the conda recipe from the local sdist (or wheel?) and automatically build the conda package during CI.

**Additional context**
If there is interest, I can try to add this feature.
I was first thing about adding a `grayskull local` subcommand but that might introduce some backward incompatibility (I think it would make sense to move some options common to `pypi` and `local` to the main parser).
An alternative is to just pass local files as `pypi_packages`. This is similar to what was done to add GitHub support.

**Comment by marcelotrevisani** [comment]
Hi, sorry for my delay
That would be very nice indeed.
I am working to do a huge refactoring in grayskull, after that we can definitely put it as a priority :)

**Comment by beenje** [comment]
Thanks! Will wait for the refactoring then.

**Comment by marcelotrevisani** [comment]
The refactoring was already integrated to the main branch
https://github.com/conda-incubator/grayskull/pull/273
