### ISSUE TITLE
[BUG] `requires_python ~= 3.6` generates incorrect python requirement

### ISSUE THREAD

**Issue by beenje** [conda-incubator/grayskull#290]
**Describe the bug**
I ran `grayskull pypi wheel-filename` and the python requirement generated was `python >=3.6,<3.7`.
The [setup.cfg](https://github.com/jwodder/wheel-filename/blob/4099de720a66854bcf2b0f02cb4f276fdb2f886a/setup.cfg#L42) includes `python_requires = ~= 3.6`, which is equivalent to `>=3.6,<4`.

**To Reproduce**
1. Run `grayskull pypi wheel-filename`

**Expected behavior**
The python requirement generated should be `>=3.6,<4` (or `>=3.6,==3.*`?)

**Environment:**
 - grayskull --version
1.1.0

**Additional context**
I tracked the issue to the `generic_py_ver_to` function.
Currently `generic_py_ver_to({"requires_python": "~=3.6"}, config) == ">=3.6,<3.7` which is incorrect.

**Comment by marcelotrevisani** [comment]
Yeah, indeed that is a bug, thanks for reporting it! Are you considering fixing it? I am asking that just to be aware :)

**Comment by beenje** [comment]
I'll give it a try :-)
