### ISSUE TITLE
[BUG] He-Man reference image missing in documentation

### ISSUE THREAD

**Issue by openSourcerer9000** [conda-incubator/grayskull#308]
I would submit a PR but the author's intent is unclear as to which He-Man related image should go there:

![image](https://user-images.githubusercontent.com/61931826/158465608-0ed40da2-a9a0-4ba7-9898-938a3ba2cb59.png)

**Comment by marcelotrevisani** [comment]
hey, it was a reference to this image
https://he-man.fandom.com/wiki/Castle_Grayskull?file=Grayskull.jpg

this image used to be in wikipedia I think, but it seems they removed it

**Comment by marcelotrevisani** [comment]
Fixed! Thanks for reporting it
