### ISSUE TITLE
[BUG] Also add NOTICE if it is present in package

### ISSUE THREAD

**Issue by BastianZim** [conda-incubator/grayskull#312]
**Describe the bug**

Some licenses ship with a separate NOTICE file. This file is currently not included, only the license is. As some licenses say that the notice should be included as well, it would be great if Grayskull could add it automatically, like it does with the license itself.

**To Reproduce**
1. Add a package

**Expected behavior**

LICENSE and NOTICE are added

**Outputs**
If applicable, add the output to help explain your problem.

Something like this:

```yaml
license_file:
  - LICENSE
  - NOTICE
``` 

**Environment:**
  Everywhere 

**Additional context**

**Comment by xylar** [comment]
I just wanted to give my support to this one.  If Grayskull detects `NOTICE` files automatically, that would save me having to redundantly download the PyPI packages to detect them as part of my automation of `apache-airflow-providers-*` packages.

**Comment by marcelotrevisani** [comment]
That can be added indeed, because for now it just searches for the "common" files or if the file is specified in the metadata of the package.

**Comment by marcelotrevisani** [comment]
related to 
https://github.com/conda-incubator/grayskull/pull/319

**Comment by marcelotrevisani** [comment]
> **Describe the bug** A clear and concise description of what the bug is.
> 
> Some licenses ship with a separate NOTICE file. This file is currently not included, only the license is. As some licenses say that the notice should be included as well, it would be great if Grayskull could add it automatically, like it does with the license itself.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Add a package
> 
> **Expected behavior** A clear and concise description of what you expected to happen.
> 
> LICENSE and NOTICE are added
> 
> **Outputs** If applicable, add the output to help explain your problem.
> 
> Something like this:
> 
> ```yaml
> license_file:
>   - LICENSE
>   - NOTICE
> ```
> 
> **Environment:** Everywhere
> 
> **Additional context** Add any other context about the problem here.

do you have a package in mind that has those two licences present?

**Comment by xylar** [comment]
Some good examples are the `apache-airflow-provider-*` packages.  Here's an arbitrary example:
https://pypi.org/project/apache-airflow-providers-databricks/

**Comment by marcelotrevisani** [comment]
the problem in having two files is that, what is the licence? because they can be different

**Comment by BastianZim** [comment]
Generally from what I saw it’s that only one is the license and the other one is a copyright disclaimer. 

Otherwise they could be joined by AND?

**Comment by marcelotrevisani** [comment]
yeah, I just merged a PR that is doing exactly what you mentioned. I also added a message when it finds multiple licences, so the user needs to review it
