### ISSUE TITLE
[BUG] https://www.marcelotrevisani.com/grayskull

### ISSUE THREAD

**Issue by BastianZim** [conda-incubator/grayskull#321]
I don't know if you're already aware of it or if this service is not available anymore but https://www.marcelotrevisani.com/grayskull is currently throwing the following: _It was not possible to generate the recipe. Internal Server Error. Please check the package name and version if they are available on PyPI._

Since this is a free service I completely understand if it's not available anymore but just wanted to quickly mention it. :)

**Comment by marcelotrevisani** [comment]
well, that should be on, let me take a look

**Comment by BastianZim** [comment]
It's working for me as well, thank you! :)

**Comment by BastianZim** [comment]
@marcelotrevisani Unfortunately, it stopped working again for me. The package I used to test is _ isbnlib_.

**Comment by marcelotrevisani** [comment]
yeah, just checked and something is crashing the django server, it needs further investigation, it might take a while :/

**Comment by BastianZim** [comment]
Poor Django... No worries, no rush from my side :)

**Comment by BastianZim** [comment]
It is working, thank you! :)

**Comment by marcelotrevisani** [comment]
> @marcelotrevisani It crashed again... Just tried it with _verstr_ and got the same error again.

I changed a few things now on the server, lets's see if it is going to persist.

I have plans to improve those things... I just don't have time 🥲

**Comment by marcelotrevisani** [comment]
it should be working now

**Comment by BastianZim** [comment]
It's working again, thank you!

> I just don't have time

Would it make sense to open source it? To be honest, I use it primarily for reviewing staged-recipes so maybe it could be incorporated there? I'd be happy to sponsor a heroku instance where this could live.

**Comment by marcelotrevisani** [comment]
yeah, it is on my plans; I just need time for that, the current implementation I cannot opensource it because it is coupled with my personal website. And there are things there that are copyright.
But I have the plans to put grayskull in restful API and create a separate website for grayskull to run on, so then I can opensource it

**Comment by marcelotrevisani** [comment]
and regarding your second questions that I missed, sorry
It is possible to integrate that to the feedstock, that is another thing that I have plans, but I don't have time for it, hahaha

**Comment by BastianZim** [comment]
If only the day would have 26 hours... 😄 No worries it's nice to have but nothing urgent! Thanks for the project being there at all!
