### ISSUE TITLE
Recipe generation fails because api.opensource.org is down

### ISSUE THREAD

**Issue by JanJaguschQC** [conda-incubator/grayskull#332]
**Describe the bug**

Running the usage example `grayskull pypi pytest` causes a `ConnectionError` because api.opensource.org is not available:

```
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.opensource.org', port=443): Max retries exceeded with url: /licenses/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x10f59a850>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
```

**Expected behavior**

I would expect the request to succeed and the recipe to be generated.

**Environment:**

```
grayskull --version
1.2.0
```

**Additional context**

I don't think that this is a bug in this package. The error is apparent: api.opensource.org is down. It's just that is has been down since yesterday and I thought maybe it's better to file this as an issue, so people are aware of it.

**Comment by marcelotrevisani** [comment]
that was fixed, I will release a new version with that fix in the upcoming days

**Comment by marcelotrevisani** [comment]
version ``1.3.0`` was released, can you please double check if it is running fine for you? if so, can you close this issue? thanks!
@JanJaguschQC

**Comment by kai-tub** [comment]
It worked for me :+1:

**Comment by JanJaguschQC** [comment]
> version `1.3.0` was released, can you please double check if it is running fine for you? if so, can you close this issue? thanks! @JanJaguschQC

It's working. Thank you!

**Comment by marcelotrevisani** [comment]
Thank you both! :)
