### ISSUE TITLE
[BUG]  In a generated recipe from the PyPI the build section is before source.

### ISSUE THREAD

**Issue by inpefess** [conda-incubator/grayskull#333]
**Describe the bug**
In a generated recipe from the PyPI the `build` section is before `source`.

**To Reproduce**
```sh
grayskull pypi requests
head requests/meta.yaml
```

**Expected behavior**
`conda-forge-linter` expects top level meta keys in the following order ['package', 'source', 'build', 'requirements', 'test', 'about', 'extra']. (See, e.g. https://github.com/conda-forge/staged-recipes/pull/19048#issuecomment-1134348803)

**Outputs**
`build` section is before `source`

**Environment:**
 - conda list
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
alabaster                 0.7.12                     py_0    conda-forge
babel                     2.10.1             pyhd8ed1ab_0    conda-forge
brotlipy                  0.7.0           py39hb9d737c_1004    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.18.1               h7f98852_0    conda-forge
ca-certificates           2022.5.18.1          ha878542_0    conda-forge
certifi                   2022.5.18.1      py39hf3d152e_0    conda-forge
cffi                      1.15.0           py39h4bc2ebd_0    conda-forge
charset-normalizer        2.0.12             pyhd8ed1ab_0    conda-forge
colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
conda-souschef            2.1.1              pyhd8ed1ab_0    conda-forge
cryptography              37.0.2           py39hd97740a_0    conda-forge
curl                      7.83.1               h7bff187_0    conda-forge
docutils                  0.16             py39hf3d152e_3    conda-forge
expat                     2.4.8                h27087fc_0    conda-forge
gettext                   0.19.8.1          h73d1719_1008    conda-forge
git                       2.35.3          pl5321h36853c3_0    conda-forge
grayskull                 1.3.0              pyhd8ed1ab_0    conda-forge
idna                      3.3                pyhd8ed1ab_0    conda-forge
imagesize                 1.3.0              pyhd8ed1ab_0    conda-forge
importlib-metadata        4.11.4           py39hf3d152e_0    conda-forge
jarowinkler               1.0.2            py39h5a03fae_3    conda-forge
jinja2                    3.1.2              pyhd8ed1ab_0    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
krb5                      1.19.3               h3790be6_0    conda-forge
ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
libblas                   3.9.0           14_linux64_openblas    conda-forge
libcblas                  3.9.0           14_linux64_openblas    conda-forge
libcurl                   7.83.1               h7bff187_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 12.1.0              h8d9b700_16    conda-forge
libgfortran-ng            12.1.0              h69a702a_16    conda-forge
libgfortran5              12.1.0              hdcd56e2_16    conda-forge
libgomp                   12.1.0              h8d9b700_16    conda-forge
libiconv                  1.16                 h516909a_0    conda-forge
liblapack                 3.9.0           14_linux64_openblas    conda-forge
libnghttp2                1.47.0               h727a467_0    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libopenblas               0.3.20          pthreads_h78a6416_0    conda-forge
libssh2                   1.10.0               ha56f1ee_2    conda-forge
libstdcxx-ng              12.1.0              ha89aaad_16    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libzlib                   1.2.11            h166bdaf_1014    conda-forge
markupsafe                2.1.1            py39hb9d737c_1    conda-forge
ncurses                   6.3                  h27087fc_1    conda-forge
numpy                     1.22.3           py39hc58783e_2    conda-forge
openssl                   1.1.1o               h166bdaf_0    conda-forge
packaging                 21.3               pyhd8ed1ab_0    conda-forge
pcre2                     10.37                h032f7d1_0    conda-forge
perl                      5.32.1          2_h7f98852_perl5    conda-forge
pip                       22.1.1             pyhd8ed1ab_0    conda-forge
pkginfo                   1.8.2              pyhd8ed1ab_0    conda-forge
progressbar2              4.0.0              pyhd8ed1ab_0    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pygments                  2.12.0             pyhd8ed1ab_0    conda-forge
pyopenssl                 22.0.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1            py39hf3d152e_5    conda-forge
python                    3.9.12          h9a8a25e_1_cpython    conda-forge
python-utils              3.2.2              pyhd8ed1ab_0    conda-forge
python_abi                3.9                      2_cp39    conda-forge
pytz                      2022.1             pyhd8ed1ab_0    conda-forge
rapidfuzz                 2.0.11           py39h1832856_0    conda-forge
readline                  8.1                  h46c0cb4_0    conda-forge
requests                  2.27.1             pyhd8ed1ab_0    conda-forge
ruamel.yaml               0.17.21          py39hb9d737c_1    conda-forge
ruamel.yaml.clib          0.2.6            py39hb9d737c_1    conda-forge
ruamel.yaml.jinja2        0.2.4                      py_1    conda-forge
setuptools                62.3.2           py39hf3d152e_0    conda-forge
snowballstemmer           2.2.0              pyhd8ed1ab_0    conda-forge
sphinx                    4.5.0              pyh6c4a22f_0    conda-forge
sphinxcontrib-applehelp   1.0.2                      py_0    conda-forge
sphinxcontrib-devhelp     1.0.2                      py_0    conda-forge
sphinxcontrib-htmlhelp    2.0.0              pyhd8ed1ab_0    conda-forge
sphinxcontrib-jsmath      1.0.1                      py_0    conda-forge
sphinxcontrib-qthelp      1.0.3                      py_0    conda-forge
sphinxcontrib-serializinghtml 1.1.5              pyhd8ed1ab_2    conda-forge
sqlite                    3.38.5               h4ff8645_0    conda-forge
stdlib-list               0.7.0                      py_2    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
tzdata                    2022a                h191b570_0    conda-forge
urllib3                   1.26.9             pyhd8ed1ab_0    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
zipp                      3.8.0              pyhd8ed1ab_0    conda-forge
zlib                      1.2.11            h166bdaf_1014    conda-forge

 - pip list
Package                       Version
----------------------------- -----------
alabaster                     0.7.12
Babel                         2.10.1
brotlipy                      0.7.0
certifi                       2022.5.18.1
cffi                          1.15.0
charset-normalizer            2.0.12
colorama                      0.4.4
conda-souschef                2.1.1
cryptography                  37.0.2
docutils                      0.16
grayskull                     1.3.0
idna                          3.3
imagesize                     1.3.0
importlib-metadata            4.11.4
jarowinkler                   1.0.2
Jinja2                        3.1.2
MarkupSafe                    2.1.1
numpy                         1.22.3
packaging                     21.3
pip                           22.1.1
pkginfo                       1.8.2
progressbar2                  4.0.0
pycparser                     2.21
Pygments                      2.12.0
pyOpenSSL                     22.0.0
pyparsing                     3.0.9
PySocks                       1.7.1
python-utils                  3.2.2
pytz                          2022.1
rapidfuzz                     2.0.11
requests                      2.27.1
ruamel.yaml                   0.17.21
ruamel.yaml.clib              0.2.6
ruamel.yaml.jinja2            0.2.4
setuptools                    62.3.2
snowballstemmer               2.2.0
Sphinx                        4.5.0
sphinxcontrib-applehelp       1.0.2
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        2.0.0
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.5
stdlib-list                   0.7.0
urllib3                       1.26.9
wheel                         0.37.1
zipp                          3.8.0

 - grayskull --version
1.3.0

**Additional context**
No

**Comment by ForgottenProgramme** [comment]
#288
