### ISSUE TITLE
[FEATURE] Install deps from pyproject/setup.cfg into active environment using conda/mamba 

### ISSUE THREAD

**Issue by tlambert03** [conda-incubator/grayskull#339]
**Is your feature request related to a problem? Please describe.**
Very often when developing (setuptools-based) packages, one sets up their local env with `pip install -e .[dev]` or something like that.  If, however, you wanted to use conda-forge to grab everything, the primary "solution" seems to be to maintain a duplicate `environment.yaml` file.  That bugs me :)

**Describe the solution you'd like**
I'd like to be able to do something like `grayskull install -e .[dev]`, and have it parse my install_requires, along with any requested extras, and use _mamba_ to install them.  Since grayskull already has all the logic to convert from pip deps to conda reps, it seems sort of in the wheelhouse here? 

**Additional context**
I hacked together a quick-and-dirty proof of principle here: https://gist.github.com/tlambert03/cdc63d68f4fd1bce20f8f3e769217759

using  `extract_requirements`, `solve_list_pkg_name`, and  `ensure_pep440_in_req_list` from this package.
Is this a feature you'd consider supporting?  If so, I'd be happy to put it together in a PR, and take your advice on cleaning it up.  If you think that sort of functionality is outside of the scope here, I understand that too.

thanks for your work!

**Comment by tlambert03** [comment]
on further thought... I do think that the full installation procedure is probably out of scope here (though curious to hear your thoughts).  What _would_ probably be useful is a slightly more public way to take a list of PyPI requirements and return a list of conda-ready requirements:

```
def condafy_requirements(requires: List[str], ...) -> List[str]:
    """Where `requires` is a list of pip requirement specifiers"""
```

**Comment by marcelotrevisani** [comment]
we can create an ``environment.yaml`` based on the run requirements or conda-lock file, but that is really out of scope of grayskull

**Comment by tlambert03** [comment]
fair enough! thanks for your time :)

**Comment by tlambert03** [comment]
(side note, proof of principle package `pamba` here, using grayskull: https://github.com/tlambert03/pamba)
