### ISSUE TITLE
[BUG] "Using .* with relational operator is superfluous and deprecated"

### ISSUE THREAD

**Issue by maresb** [conda-incubator/grayskull#348]
Consider the package [`dbt-core`](https://pypi.org/project/dbt-core/#files). The `install_requires` contains

```python
        "dbt-extractor~=0.4.1",
```

[Running Grayskull](https://marcelotrevisani.info:8000/recipe/?name=dbt-core&version=1.1.1) this gets translated into

```yaml
    - dbt-extractor >=0.4.1,==0.4.*
```

Then running boa with `conda mambabuild -c conda-forge .` or `conda build -c conda-forge .` produces the warning

```
WARNING:conda.models.version:Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 0.4.*, but conda is ignoring the .* and treating it as 0.4
```

This results in the unsatisfiable dependency `>=0.4.1,==0.4` since `==0.4` seems to imply 0.4.0 and excludes 0.4.1.

Interestingly, if I change it to a single equals (`>=0.4.1,=0.4.*`) then it doesn't complain and seems to work as intended.

**Comment by marcelotrevisani** [comment]
true, it does need some work, actually this part can be ``~=``
we have moved that because a request came up, but I think we should follow what conda does and ``~=`` is good enough

**Comment by maresb** [comment]
Is there any reason why `~=` is avoided in Conda recipes? Does it not work reliably, or was it only recently implemented?

**Comment by BastianZim** [comment]
`~=` is not supported by conda-build: https://docs.conda.io/projects/conda-build/en/latest/resources/package-spec.html#build-version-spec

Conda-forge just monkey patches it, iirc.

**Comment by maresb** [comment]
Thanks @BastianZim! Then `~=` is not an option.

Then it seems like there are two possibilities for converting `~=0.4.1`:

```
>=0.4.1,<0.5
>=0.4.1,=0.4.*
```

The second one looks really confusing to me. Does the first one correctly handle prereleases? In other words, is `0.5b1<0.5`? If so, then we'll need some obscure incantation to correctly deal with that case, right?

**Comment by BastianZim** [comment]
Well, python recommends `>= V.N, == V.*` so I guess/hope that should work?

Ref: https://peps.python.org/pep-0440/#compatible-release

**Comment by BastianZim** [comment]
MIght be easier to discuss with core again if we just go with `~=`. What do you think @marcelotrevisani since you're core and developer. 😄

**Comment by BastianZim** [comment]
> As I point out above, this unfortunately doesn't work with Conda:

Ahh true sorry forgot

> How would this work if it's not supported by conda-build?

From what I remember, this is monkey patched in conda-forge. Since that's the only location where the recipe would be, it should be fine.

**Comment by maresb** [comment]
Sometimes I'll run `conda mambabuild recipe` locally when testing a really problematic recipe. It seems like it would be really confusing if it failed locally but ran on CF.

**Comment by marcelotrevisani** [comment]
yeah, as @BastianZim had mentioned, it would be better to fix it by putting ``>= V.N, == V.*``
so, it needs a bit of work

**Comment by maresb** [comment]
Do you mean `>= V.N, = V.*`? (As I have mentioned above, `>= V.N, == V.*` doesn't seem to work properly with conda.)

**Comment by marcelotrevisani** [comment]
> Do you mean `>= V.N, = V.*`? (As I have mentioned above, `>= V.N, == V.*` doesn't seem to work properly with conda.)

Sorry, that should be ``>= V.N, < V+1.0`` then

**Comment by maresb** [comment]
I strongly suspect that `>= V.N, < (V+1).0` is still incorrect due to prerelease versions.

I just found [this](https://docs.conda.io/projects/conda/en/latest/user-guide/concepts/pkg-specs.html#predictable-version-ordering) where it seems to be quite the logic puzzle to deduce the minimal version string which is greater than `V.*`. I think we need something like `>= V.N, < (V+1)dev`, but I'm not entirely satisfied by the examples given in that link.

Maybe I can find the relevant classes in Conda's source so that I can test these things myself...

**Comment by marcelotrevisani** [comment]
To be honest, I am not taking care much of pre-release versions because they shouldn't be in conda-forge in general.

The dev can be added, it will need more tests.

**Comment by maresb** [comment]
Makes sense. Thinking about it from that perspective, adding this obscure `dev` suffix certainly makes the recipe more confusing and less readable. That's a steep price to pay for handling edge cases which are virtually nonexistent. Thanks for the explanation!

And the root of this issue seems like a bug in `conda-build`...

**Comment by BastianZim** [comment]
> And the root of this issue seems like a bug in conda-build...

That’s what I was thinking. Maybe it’s easier to add support to conda-build for `~=`

**Comment by maresb** [comment]
Ya, it seems that there was [this attempt](https://github.com/conda/conda-build/pull/4113), but for some subtle reason it's not working properly.

If we fix it upstream, then it'll only work properly for people who have up-to-date versions of conda-build. But I suppose we care primarily about conda-forge, where this isn't a problem.

**Comment by BastianZim** [comment]
> But I suppose we care primarily about conda-forge, where this isn't a problem.

Yes. The only ones that would have to update are people like you who use it for testing but I guess you create fresh environments for that anyways?

**Comment by maresb** [comment]
> but I guess you create fresh environments for that anyways

Honestly not so often. I just run `conda activate forge` where I have Grayskull, Boa, and a few other tools. There's not much point to updating when things are working. And then if it does break, I'm going to try to update Grayskull, which doesn't depend on `conda-build`. I've only ever updated `conda-build` when I've already spent an hour trying to figure out why a recipe is succeeding on CF but failing locally. 

From this perspective, if we fix `~=` in `conda-build`, it may make sense to add a minimal version of `conda-build` to `run_constrained` requirements so that in case `conda-build` is installed it'll be updated.

**Comment by BastianZim** [comment]
Oh yeah that’s maybe not a bad idea at all! @marcelotrevisani What do you think?

**Comment by maresb** [comment]
Hold on, perhaps the situation has changed over the past few years...

> `~=` is not supported by conda-build: https://docs.conda.io/projects/conda-build/en/latest/resources/package-spec.html#build-version-spec

I just checked this, and it _does_ appear to work, even though it's not documented. :confused: Presumably it was added for [v3.20.5](https://github.com/conda/conda-build/releases/tag/3.20.5) in the PR linked above (the first bullet point under "Bug fixes:".

Therefore, I think we can solve this by using `~=` in the recipe and adding `run_constrained: conda-build >=3.20.5` to the Grayskull recipe (and adding tests...).

**Comment by maresb** [comment]
PR to add `run_constrained`: https://github.com/conda-forge/grayskull-feedstock/pull/55

**Comment by jaimergp** [comment]
The problem with `~=` is that it shouldn't make it to the repodata.json files, because older `conda` clients won't be able to parse it and error out. IIRC, this operator is patched out during the CDN cloning (when repodata patches are applied).

There's also one problem with roundtripped MatchSpec objects. `name=1.2` is parsed correctly, but when converted back to string, it can appear as `name==1.2`, so it's not the same anymore. Unfortunately, `conda` does this to sanitize inputs, so one need to be careful.

**Comment by maresb** [comment]
@jaimergp thanks for the info! Yikes, that sounds like a mess. Does the repodata patching work well enough that it's safe to use `~=` in recipes?

If not, do you have any suggestions on how we could better solve this problem?

Perhaps we should revert this and try for one of the other messier solutions?

**Comment by jaimergp** [comment]
I don't think we have audited every possibility, but that's the main issue: back-compatibility. The repodata patch only covers the channel repodata.json, but the metadata in the tarball will be still the same, which might leak into the `PrefixData` object used to parse the installed packages (although in some circumstances the data might come from the repodata, I don't have a very clear idea on when this happens).

When we discussed this in a core call some months ago I recall that the consensus was to avoid its use whenever possible, and use t[he more verbose but back compatible syntax](https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/blob/6e2ed70bd0eaaf283bb1e981836778f2b982f324/recipe/gen_patch_json.py#L1904): `~=1.4` gets translated to `>=1.4,<2.0a`, iirc.

With respect to the round trip issues in `MatchSpec`, Wolf started some work on https://github.com/conda/conda/pull/9980, and I'd like to resume it in the next weeks, so hopefully this will become less of an issue.

**Comment by BastianZim** [comment]
I think, I just bumped into this (or at least it's related). 

One of my feedstocks has the requirements `~=0.9.0` which gets translated to `>=0.9.0,==0.9.*`.
This makes the solves throw an error despite `v0.9.6` being available. 

PR: https://github.com/conda-forge/aiofile-feedstock/pull/3
Logs: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=548936&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d

**Comment by maresb** [comment]
Ya, sure sounds like it. I'm working at the moment on figuring out how to compute the upper bound string... and reading up on `packaging`. (My current idea is to parse the version, increment the first nonzero of major/minor/patch, make alpha, and output to a canonical string. Suggestions welcome.)

**Comment by maresb** [comment]
First attempt at new fix: https://github.com/conda-incubator/grayskull/pull/368
