### ISSUE TITLE
 https://www.marcelotrevisani.com/grayskull is down

### ISSUE THREAD

**Issue by BastianZim** [conda-incubator/grayskull#363]
Currently fails with _Error - package_name Load failed_

Sorry, I know that it's free so no rush – just wanted to mention it here. :)

**Comment by marcelotrevisani** [comment]
thanks for reporting it! gonna take a look at it in a few hours

Thanks for the heads up! :)

**Comment by BastianZim** [comment]
Thank you! :)

**Comment by marcelotrevisani** [comment]
Sorry, I got lost this past days in my day job, gonna take a look at it now

**Comment by marcelotrevisani** [comment]
It is working again! I am not sure what happened, but yeah, it is working!
Thanks for reporting! if it does not work fro you please let me know

**Comment by BastianZim** [comment]
Working perfectly. Thank you very much! :)
