### ISSUE TITLE
[BUG] C++ compiler requirement not detected

### ISSUE THREAD

**Issue by jonashaag** [conda-incubator/grayskull#364]
**Describe the bug**

For `xbcausalforest` grayskull detects that a C compiler is required when C++ compiler is required.

**To Reproduce**

```
grayskull pypi "xbcausalforest==0.1.3"
```

=>

```
...
requirements:
  build:
    - {{ compiler('c') }}
```

**Expected behavior**
Should detect `compiler('cxx')`. There are `.cpp` files in the tarball and there is `language="c++"` in `setup.py`.

**Comment by marcelotrevisani** [comment]
Indeed, gonna add it to my todo list in the upcoming weeks. Thanks for reporting it!
