### ISSUE TITLE
[BUG] grayskull 1.6.0 fails to add minimum "safe" python on noarch packages

### ISSUE THREAD

**Issue by ocefpaf** [conda-incubator/grayskull#366]
The `humre` is a norach package but fails to specify a minimum python requirement. In the past grayskull, with the `--strict-conda-forge`, used to add the `>=3.6` automatically but that is no longer true:

``` 
grayskull pypi --strict-conda-forge humre
```

**Comment by marcelotrevisani** [comment]
Fixed! Thanks for reporting it

**Comment by ocefpaf** [comment]
That was fast!
