### ISSUE TITLE
[BUG] Missed `noarch` with pins for Python versions not supported by conda-forge

### ISSUE THREAD

**Issue by jonashaag** [conda-incubator/grayskull#373]
[Here](https://github.com/jonashaag/klaus/blob/b163b77087e5ea346fa25ac74fc8046acc107684/setup.py#L24-L25) we have the following dependency pin:

```
    'dulwich>=0.19.3;python_version>="3.5"',
    'dulwich>=0.19.3,<0.20;python_version<"3.5"',
```

It makes Grayskull output a non-`noarch` package. But for conda-forge purposes I think the pin could be simplified to

```
    'dulwich>=0.19.3',
```

**Comment by marcelotrevisani** [comment]
it is removing the norach because of the selector, it indeed can be improved. Thanks for reporting it

**Comment by marcelotrevisani** [comment]
actually, it should strip that selector just in case the ``--strict-conda-forge`` is passed, otherwise the selector should remain
