### ISSUE TITLE
[BUG] grayskull is failing to add  python_requires info to the recipe.

### ISSUE THREAD

**Issue by ocefpaf** [conda-incubator/grayskull#391]
**Describe the bug**

Grayskull is  failing to add `python_requires` to recipes that declare it  in setup.py.

**To Reproduce**
1. grayskull pypi --strict-conda-forge algviz

**Expected behavior**
`python >=3.7,<3.10` in `host` and `run`.

**Outputs**
`python >=3.7` only.

**Environment:**
 - grayskull --version 1.8.2

**Additional context**
Tested a few other recipes. All failed to add `python_requires` correctly.

**Comment by maresb** [comment]
I noticed this too, and I have a suspicion that my recent changes may have somehow clobbered this. I'll try to take a look tonight.

**Comment by maresb** [comment]
Looks like I'm innocent for now. :sweat_smile: It was also not working on v1.7.0, before I made the changes. (Sorry I don't have time at the moment to do a more detailed tracethrough.)

**Comment by marcelotrevisani** [comment]
it should be ``<=3.10``, no?
I believe that is why grayskull ``--strict-conda-forge`` didn't add the upper bound.
