### ISSUE TITLE
Getting test dependencies from extras

### ISSUE THREAD

**Issue by jakirkham** [conda-incubator/grayskull#429]
AFAIK there is no standard for handling testing dependencies (with `test_requires` being dropped ( https://github.com/pypa/setuptools/issues/931 )). That said, have seen [`testing`]( https://github.com/pytest-dev/pytest/blob/ca40380e99c2cdaab1d0c041f9f28cff37ef8ff9/setup.cfg#L68 ), [`test`]( https://github.com/pypa/flit/blob/9bca11576cb75dc5b8bf862519cb134842092723/pyproject.toml#L27 ), and [`tests`]( https://github.com/holoviz/holoviz/blob/afeb5f5756d09a9d1ff1fd69f8418baccbaa05dd/setup.cfg#L53 ). Currently Grayskull checks one approach. Though maybe all of them should be checked.

https://github.com/conda-incubator/grayskull/blob/d17444d66ebf50fdb5d97948c7ecfc654b0f68fa/grayskull/strategy/pypi.py#L168

https://github.com/conda-incubator/grayskull/blob/d17444d66ebf50fdb5d97948c7ecfc654b0f68fa/grayskull/strategy/py_toml.py#L22-L24

**Comment by marcelotrevisani** [comment]
Indeed! It should check all the options, thanks for the heads up!
