### ISSUE TITLE
Project URLs naming?

### ISSUE THREAD

**Issue by jakirkham** [conda-incubator/grayskull#435]
There are a few syntaxes for project URLs in Grayskull atm. Looks like [Setuptools goes with `project_urls`]( https://setuptools.pypa.io/en/latest/userguide/declarative_config.html?highlight=project_urls#metadata ). Should we go with that here? 

https://github.com/conda-incubator/grayskull/blob/0e51e0205586acf61b10c06370d3f222cd724bf8/grayskull/strategy/py_base.py#L714

https://github.com/conda-incubator/grayskull/blob/0e51e0205586acf61b10c06370d3f222cd724bf8/grayskull/strategy/pypi.py#L280

https://github.com/conda-incubator/grayskull/blob/0e51e0205586acf61b10c06370d3f222cd724bf8/setup.py#L69

**Comment by jakirkham** [comment]
Should add this seems to result in the `about/home` URL being missed for the `pyproject.toml` case

**Comment by marcelotrevisani** [comment]
indeed, I missed that, gonna fix it, thanks
