### ISSUE TITLE
[BUG] Inconsistent name and output directory for R package recipes

### ISSUE THREAD

**Issue by jdblischak** [conda-incubator/grayskull#437]
**Describe the bug**

The recipe names and output directories produced by `grayskull cran` can be inconsistent based on the command-line argument spelling of the package name

**To Reproduce**

Using the R package [matrixStats](https://cran.r-project.org/package=matrixStats) as an example:

```sh
# recipe name: r-matrixStats
# output directory: matrixStats
grayskull cran --strict-conda-forge matrixStats
grep name matrixStats/meta.yaml
## {% set name = "matrixStats" %}
##   name: r-{{ name }}
rm -r matrixStats/

# recipe name: r-matrixstats
# output directory: matrixstats
grayskull cran --strict-conda-forge matrixstats
grep name matrixstats/meta.yaml
## {% set name = "matrixstats" %}
##   name: r-{{ name }}
rm -r matrixstats/

# recipe name: r-r-matrixstats
# output directory: matrixstats
grayskull cran --strict-conda-forge r-matrixstats
grep name matrixstats/meta.yaml
## {% set name = "r-matrixstats" %}
##   name: r-{{ name }}
rm -r matrixstats/
```

**Expected behavior**

Absent compelling motivation, I would expect `grayskull cran` to behave like `conda skeleton cran` in regards to naming conventions. This will make the eventual transition to grayskull a much smoother experience for conda R users. 

No matter the input format (matrixStats, matrixstats, r-matrixstats), both the recipe name and the output directory are always "r-matrixstats".

```sh
conda skeleton cran matrixStats
grep name r-matrixstats/meta.yaml
##   name: r-matrixstats
rm -r r-matrixstats/

conda skeleton cran matrixstats
grep name r-matrixstats/meta.yaml
##   name: r-matrixstats
rm -r r-matrixstats/

conda skeleton cran r-matrixstats
grep name r-matrixstats/meta.yaml
##   name: r-matrixstats
rm -r r-matrixstats/
```

**Environment:**
 
```sh
conda build --version
## conda-build 3.23.3

grayskull --version
## 2.2.0

python --version
## Python 3.10.8

conda --version
## conda 22.11.1
```

**Additional context**

I help maintain the repository [conda_r_skeleton_helper](https://github.com/bgruening/conda_r_skeleton_helper), which is currently the [recommended method](https://conda-forge.org/docs/maintainer/adding_pkgs.html#generating-the-recipe) for submitting R package recipes to conda-forge. The scripts are hacky, and we'd love to make them obsolete. Thus I am very interested in replacing them with grayskull once its support for R recipes is mature.

xref: #7, #349, #423

**Comment by marcelotrevisani** [comment]
Hi @jdblischak , thanks for reporting it! Indeed, that was a mistake on my side, I will fix it.
Grayskull for R is not mature yet, when you compare it to that script or conda skeleton, but we have plans to improve it. Contributions and reports regarding issues or improvements are very much appreciated!

**Comment by marcelotrevisani** [comment]
If you could open multiple issues of things that are missing or can be improved, it would help us a lot to track all missing features or future features that can be added!  :)
