### ISSUE TITLE
Add support for toml

### ISSUE THREAD

**Issue by marcelotrevisani** [conda-incubator/grayskull#45]

**Comment by marcelotrevisani** [comment]
Test with ``vega`` package
cc: @ocefpaf

**Comment by marcelotrevisani** [comment]
test with ``tzdata`` as well

**Comment by dillonroach** [comment]
I'm going to take some time and give this and #322 a whirl - just wanted to put my name in the hat so I don't duplicate effort from somebody else/vice-versa

**Comment by jakirkham** [comment]
Tried this out with [the `dask-cuda` recipe]( https://github.com/conda-forge/dask-cuda-feedstock/blob/main/recipe/meta.yaml ) and noticed the following:

* The [`project.scripts`]( https://github.com/rapidsai/dask-cuda/blob/bdb7b565e92eb79080eadd82482bdac9d1ca0c64/pyproject.toml#L41-L43 ) are missed
* The [`project.urls`]( https://github.com/rapidsai/dask-cuda/blob/bdb7b565e92eb79080eadd82482bdac9d1ca0c64/pyproject.toml#L56-L57 ) are missed

The other things are not necessarily wrong (`build/number` order, dropping some `import`s from `test`). Others Grayskull is doing something smart (`dask-core` replacement for `dask`), but the recipe maintainers may prefer to deviate.

<details>
<summary>Diff:</summary>

```diff
 build:
-  number: 0
   noarch: python
   script: {{ PYTHON }} -m pip install . -vv
-  entry_points:
-    - dask-cuda-worker = dask_cuda.cli.dask_cuda_worker:go
+  number: 0
 
 requirements:
   host:
@@ -23,32 +21,28 @@ requirements:
     - pip
   run:
     - python >=3.8
-    - dask ==2022.11.1
+    - dask-core ==2022.11.1
     - distributed ==2022.11.1
     - pynvml >=11.0.0
     - numpy >=1.18.0
     - numba >=0.54
     - pandas >=1.0
     - zict >=0.1.3
-    - __linux
 
 test:
   imports:
     - dask_cuda
-    - dask_cuda.benchmarks
   commands:
     - pip check
-    - dask-cuda-worker --help
   requires:
     - pip
 
 about:
-  home: https://github.com/rapidsai/dask-cuda
+  home: https://pypi.org/project/dask-cuda/
   summary: Utilities for Dask and CUDA interactions
   license: Apache-2.0
   license_file: LICENSE
```

</details>

**Comment by marcelotrevisani** [comment]
related to https://github.com/conda-incubator/grayskull/pull/425
