### ISSUE TITLE
Generate recipe from Cran

### ISSUE THREAD

**Issue by marcelotrevisani** [conda-incubator/grayskull#7]
Generate recipe based on the ``Cran`` repository for ``R`` packages. 
``Bioconda`` already has its own implementation of ``skeleton``. It would be interesting to discuss with them to adapt their code to this new structure.

**Comment by jdblischak** [comment]
@marcelotrevisani Thanks for your work on this. I look forward to the revamped CRAN skeleton.

I wanted to highlight an Issue with the current version of the skeleton. It can't handle the case where a package links to multiple other packages: https://github.com/conda/conda-build/issues/3499

**Comment by marcelotrevisani** [comment]
Nice, thanks for letting me know!
I think it will take me a while to implement the skeleton for R, but it is definitely on my plans!
I still need to cover some scenarios for ``PyPI`` and also to I need to do some refactoring to the project to be more flexible to load recipe. After that I will tackle the recipe generator for ``R`` looking for the CRAN repository.

Anything which you think is missing in the current skeleton or it is important to have, please feel free to open an issue. It will help me to track the whole features which we need for ``R``

**Comment by marcelotrevisani** [comment]
I am closing this as grayskull since 2.0.0 added initial support for R recipes
